export const DRIVER_FULL_ADD = 'DRIVER_FULL_ADD';
export const DRIVER_PART_ADD = 'DRIVER_PART_ADD';

export const VEHICLE_EMPTY_ADD = 'VEHICLE_EMPTY_ADD';
export const VEHICLE_TASK_ADD = 'VEHICLE_TASK_ADD';
export const VEHICLE_HEAVY_ADD = 'VEHICLE_HEAVY_ADD';
export const VEHICLE_OFFLINE_ADD = 'VEHICLE_TOFFLINEADD';